# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e9450f0058714526ae71e346446f48cf14550d3e21bd217db68d17f0708e335a9c880a6515e881c64c5eb8b58c602ea01b37f958712170944127e8cc8c6a2c1

test:
  secret_key_base: d80dabac24e0da9da56b08a946ce26792c125c7ef16126c0ab31221dd1fc26072c97adfcf8f0d5b6dd3c1e7a498e68221f98e879c3742202b2d9e496318229ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
